name: List Dev Container Features
description: 📃 List all features in a monorepo in a GitHub Action
inputs:
  path:
    default: .
outputs:
  features:
    value: ${{ steps.main.outputs.features }}
  changed-features:
    value: ${{ steps.main.outputs.changed-features }}
runs:
  using: composite
  steps:
    - shell: bash
      run: sudo apt update && sudo apt-get install -y tree jq
    - id: paths-filter
      uses: dorny/paths-filter@v2
      with:
        list-files: json
        filters: |
          src: 
            - ${{ inputs.path }}/src/*/**
          test: 
            - ${{ inputs.path }}/test/*/**
    - id: main
      run: '"$GITHUB_ACTION_PATH/mainw"'
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
        PATHS_FILTER_OUTPUTS_SRC_FILES: ${{ toJSON(steps.paths-filter.outputs.src_files) }}
        PATHS_FILTER_OUTPUTS_TEST_FILES: ${{ toJSON(steps.paths-filter.outputs.test_files) }}
